### ISSUE TITLE
Debatable choices in sparse model

### ISSUE THREAD

**Issue by pveber** [vlanore/diffsel#1]
- [x] fitness inverse rate parameter (m_a): uniformDirichlet
- [x] fitness shape parameter: 1
- [x] hyperparameters for probconv (pi_k), lambda_k and mu_k: log normal(0,1)
- [x] Random::beta from Random::gamma
- [x] fitness[aastate] + 1e-6;
- [x] moveFitness: move one random AA at each site for given cond?

**Comment by vlanore** [comment]
Regarding the beta from gamma point, what we meant is that we used this relation: https://math.stackexchange.com/a/190695
in order to draw from a beta distribution using the existing gamma implementation (as beta was absent from Random.cpp).

**Comment by vlanore** [comment]
Closing issue (outdated).
