### ISSUE TITLE
how to determine the exact amino acid with different effect strength

### ISSUE THREAD

**Issue by kanglizhu** [vlanore/diffsel#4]
Hello,
After running readdiffsel, i checked the *.signdiffsel file. This file contains four colums: site number, aminoacid number, "convergence probability", and effect strength. 

Site number ranges from 0 to  (total_base_numbers/3 -1 ), and "site number  + 1" is the position in the sequence alignment. 

From a series of "*.signdiffsel files",  i find the amino acid number ranges from 0 to 19. Now if i want to know the exact amino acid for one animo acid number, can you please explain what should i do next? 
 
Best wishes,
kangli

**Comment by vlanore** [comment]
Hello,

Aminoacids are ordered this way in diffsel:
```{'a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm','n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'y', '-'};```
So for example aminoacid 4 would be `f`, 19 would be `y`.

Sorry this wasn't explained in the README.
I hope this answers your question.

**Comment by kanglizhu** [comment]
Hello，

Thank you so much for your help. Now i know clearly how to get the exact amino acids.

Best wishes,
kangli
